// <auto-generated/>
// Generated from src/openapi.json (Subiekt 123 API v1.1)
// Do not edit manually — regenerate via: dotnet run --project tools/ContractGenerator

#nullable enable

using System.Text.Json.Serialization;

[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Subiekt.Connector.IntegrationTests")]

namespace Subiekt.Connector.Contracts;

/// <summary>Paged response wrapper for list endpoints.</summary>
public record PagedResult<T>(
    [property: JsonPropertyName("items")] List<T>? Items,
    [property: JsonPropertyName("totalItemsCount")] int TotalItemsCount
);

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum CalculationMethod
{
    Net,
    Gross,
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ClientKind
{
    Company,
    Person,
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum CommunityTransaction
{
    SK,
    SUPTK,
    OO,
    WDT,
    ET,
    DPTK,
    WSTO_OSS,
    WSTO_SK,
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum DiscountKind
{
    None,
    Percentage,
    Quota,
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum DocumentClientKind
{
    Company,
    Person,
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum DocumentKind
{
    Invoice,
    Receipt,
    Proforma,
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum InvoiceMode
{
    Traditional,
    Ksef,
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum PaymentMethod
{
    Cash,
    CashOnDelivery,
    BankTransfer,
    CreditCard,
    ElectronicPayment,
    Setoff,
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum PaymentState
{
    Paid,
    Unpaid,
    Overdue,
    NotSubjectToPayment,
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ProductKind
{
    Good,
    Service,
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum SellerKind
{
    Company,
    Person,
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum SplitPayment
{
    False,
    True,
    ManualTrue,
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum TinKind
{
    Nip,
    Vatin,
    Pesel,
}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum VatReleaseReason
{
    Art113Ustep1i9UstawyOVat,
    Art49Ustep1i9UstawyOVat,
    Art82Ustep3UstawyOVat,
    Custom,
}

public record AddressDto(
    [property: JsonPropertyName("country")]
    string Country,
    [property: JsonPropertyName("city")]
    string? City = null,
    [property: JsonPropertyName("line1")]
    string? Line1 = null,
    [property: JsonPropertyName("name")]
    string? Name = null,
    [property: JsonPropertyName("zipCode")]
    string? ZipCode = null
);

public record ClientBankAccountDto(
    [property: JsonPropertyName("bankName")]
    string? BankName = null,
    [property: JsonPropertyName("default")]
    bool? Default = null,
    [property: JsonPropertyName("number")]
    string? Number = null
);

public record ClientDto(
    [property: JsonPropertyName("address")]
    AddressDto? Address = null,
    [property: JsonPropertyName("associatedClient")]
    bool? AssociatedClient = null,
    [property: JsonPropertyName("bankAccounts")]
    List<ClientBankAccountDto>? BankAccounts = null,
    [property: JsonPropertyName("buyerId")]
    Guid? BuyerId = null,
    [property: JsonPropertyName("defaultDiscount")]
    decimal? DefaultDiscount = null,
    [property: JsonPropertyName("defaultDueDate")]
    int? DefaultDueDate = null,
    [property: JsonPropertyName("defaultPaymentMethod")]
    PaymentMethod? DefaultPaymentMethod = null,
    [property: JsonPropertyName("deliveryAddress")]
    AddressDto? DeliveryAddress = null,
    [property: JsonPropertyName("emails")]
    List<string>? Emails = null,
    [property: JsonPropertyName("favourite")]
    bool? Favourite = null,
    [property: JsonPropertyName("group")]
    string? Group = null,
    [property: JsonPropertyName("id")]
    Guid? Id = null,
    [property: JsonPropertyName("kind")]
    ClientKind? Kind = null,
    [property: JsonPropertyName("name")]
    string? Name = null,
    [property: JsonPropertyName("note")]
    string? Note = null,
    [property: JsonPropertyName("phone1")]
    string? Phone1 = null,
    [property: JsonPropertyName("phone2")]
    string? Phone2 = null,
    [property: JsonPropertyName("skype")]
    string? Skype = null,
    [property: JsonPropertyName("tin")]
    string? Tin = null,
    [property: JsonPropertyName("tinKind")]
    TinKind? TinKind = null,
    [property: JsonPropertyName("website")]
    string? Website = null
);

public record ClientExternalId(
    [property: JsonPropertyName("value")]
    Guid? Value = null
);

public record ClientListItemDto(
    [property: JsonPropertyName("address")]
    AddressDto? Address = null,
    [property: JsonPropertyName("favourite")]
    bool? Favourite = null,
    [property: JsonPropertyName("group")]
    string? Group = null,
    [property: JsonPropertyName("id")]
    Guid? Id = null,
    [property: JsonPropertyName("kind")]
    ClientKind? Kind = null,
    [property: JsonPropertyName("name")]
    string? Name = null,
    [property: JsonPropertyName("tin")]
    string? Tin = null,
    [property: JsonPropertyName("tinKind")]
    TinKind? TinKind = null
);

public record CreateClientDto(
    [property: JsonPropertyName("name")]
    string Name,
    [property: JsonPropertyName("address")]
    AddressDto? Address = null,
    [property: JsonPropertyName("associatedClient")]
    bool? AssociatedClient = null,
    [property: JsonPropertyName("bankAccounts")]
    List<ClientBankAccountDto>? BankAccounts = null,
    [property: JsonPropertyName("buyerId")]
    Guid? BuyerId = null,
    [property: JsonPropertyName("defaultDiscount")]
    decimal? DefaultDiscount = null,
    [property: JsonPropertyName("defaultDueDate")]
    int? DefaultDueDate = null,
    [property: JsonPropertyName("defaultPaymentMethod")]
    PaymentMethod? DefaultPaymentMethod = null,
    [property: JsonPropertyName("deliveryAddress")]
    AddressDto? DeliveryAddress = null,
    [property: JsonPropertyName("emails")]
    List<string>? Emails = null,
    [property: JsonPropertyName("favourite")]
    bool? Favourite = null,
    [property: JsonPropertyName("group")]
    string? Group = null,
    [property: JsonPropertyName("kind")]
    ClientKind? Kind = null,
    [property: JsonPropertyName("note")]
    string? Note = null,
    [property: JsonPropertyName("phone1")]
    string? Phone1 = null,
    [property: JsonPropertyName("phone2")]
    string? Phone2 = null,
    [property: JsonPropertyName("skype")]
    string? Skype = null,
    [property: JsonPropertyName("tin")]
    string? Tin = null,
    [property: JsonPropertyName("tinKind")]
    TinKind? TinKind = null,
    [property: JsonPropertyName("website")]
    string? Website = null
);

public record CreateClientResultDto(
    [property: JsonPropertyName("id")]
    ClientExternalId? Id = null
);

public record CreateDocumentDto(
    [property: JsonPropertyName("currency")]
    string Currency,
    [property: JsonPropertyName("issuer")]
    string Issuer,
    [property: JsonPropertyName("bankAccount")]
    DocumentBankAccountDto? BankAccount = null,
    [property: JsonPropertyName("bankAccountPln")]
    DocumentBankAccountDto? BankAccountPln = null,
    [property: JsonPropertyName("buyer")]
    DocumentCreateClientDto? Buyer = null,
    [property: JsonPropertyName("calculationMethod")]
    CalculationMethod? CalculationMethod = null,
    [property: JsonPropertyName("cashBasis")]
    bool? CashBasis = null,
    [property: JsonPropertyName("client")]
    DocumentCreateClientDto? Client = null,
    [property: JsonPropertyName("communityTransaction")]
    CommunityTransaction? CommunityTransaction = null,
    [property: JsonPropertyName("customVatReleaseReason")]
    string? CustomVatReleaseReason = null,
    [property: JsonPropertyName("deliveryAddress")]
    AddressDto? DeliveryAddress = null,
    [property: JsonPropertyName("deliveryDate")]
    DateTime? DeliveryDate = null,
    [property: JsonPropertyName("dueDate")]
    DateTime? DueDate = null,
    [property: JsonPropertyName("dueDateDescription")]
    string? DueDateDescription = null,
    [property: JsonPropertyName("eInvoice")]
    bool? EInvoice = null,
    [property: JsonPropertyName("exchangeRate")]
    ExchangeRateDto? ExchangeRate = null,
    [property: JsonPropertyName("issueDate")]
    DateTime? IssueDate = null,
    [property: JsonPropertyName("items")]
    List<CreateDocumentItemDto>? Items = null,
    [property: JsonPropertyName("jpkVatGroups")]
    List<string>? JpkVatGroups = null,
    [property: JsonPropertyName("kind")]
    DocumentKind? Kind = null,
    [property: JsonPropertyName("note")]
    string? Note = null,
    [property: JsonPropertyName("orderDate")]
    DateTime? OrderDate = null,
    [property: JsonPropertyName("paymentMethod")]
    PaymentMethod? PaymentMethod = null,
    [property: JsonPropertyName("payments")]
    List<PaymentDto>? Payments = null,
    [property: JsonPropertyName("recipient")]
    string? Recipient = null,
    [property: JsonPropertyName("splitPayment")]
    SplitPayment? SplitPayment = null,
    [property: JsonPropertyName("taxLiabilityDate")]
    DateTime? TaxLiabilityDate = null,
    [property: JsonPropertyName("transactionLocation")]
    string? TransactionLocation = null,
    [property: JsonPropertyName("vatReleaseReason")]
    VatReleaseReason? VatReleaseReason = null,
    [property: JsonPropertyName("wstoAdditionalInformation")]
    string? WstoAdditionalInformation = null,
    [property: JsonPropertyName("wstoConsumerCountry")]
    string? WstoConsumerCountry = null,
    [property: JsonPropertyName("wstoShipmentCountry")]
    string? WstoShipmentCountry = null
);

public record CreateDocumentItemDto(
    [property: JsonPropertyName("productName")]
    string ProductName,
    [property: JsonPropertyName("unit")]
    string Unit,
    [property: JsonPropertyName("vatRate")]
    string VatRate,
    [property: JsonPropertyName("barcode")]
    string? Barcode = null,
    [property: JsonPropertyName("cnCode")]
    string? CnCode = null,
    [property: JsonPropertyName("discount")]
    decimal? Discount = null,
    [property: JsonPropertyName("discountKind")]
    DiscountKind? DiscountKind = null,
    [property: JsonPropertyName("grossPrice")]
    decimal? GrossPrice = null,
    [property: JsonPropertyName("gtu")]
    string? Gtu = null,
    [property: JsonPropertyName("netPrice")]
    decimal? NetPrice = null,
    [property: JsonPropertyName("no")]
    int? No = null,
    [property: JsonPropertyName("note")]
    string? Note = null,
    [property: JsonPropertyName("pkwiu")]
    string? Pkwiu = null,
    [property: JsonPropertyName("quantity")]
    decimal? Quantity = null,
    [property: JsonPropertyName("sourceProductId")]
    Guid? SourceProductId = null,
    [property: JsonPropertyName("symbol")]
    string? Symbol = null
);

public record CreateDocumentResultDto(
    [property: JsonPropertyName("id")]
    DocumentExternalId? Id = null
);

public record CreateProductDto(
    [property: JsonPropertyName("name")]
    string Name,
    [property: JsonPropertyName("unit")]
    string Unit,
    [property: JsonPropertyName("vatRate")]
    string VatRate,
    [property: JsonPropertyName("barcode")]
    string? Barcode = null,
    [property: JsonPropertyName("cnCode")]
    string? CnCode = null,
    [property: JsonPropertyName("description")]
    string? Description = null,
    [property: JsonPropertyName("favourite")]
    bool? Favourite = null,
    [property: JsonPropertyName("fiscalName")]
    string? FiscalName = null,
    [property: JsonPropertyName("group")]
    string? Group = null,
    [property: JsonPropertyName("jpkVatGroups")]
    List<string>? JpkVatGroups = null,
    [property: JsonPropertyName("kind")]
    ProductKind? Kind = null,
    [property: JsonPropertyName("ossVatRates")]
    List<OssVatRateDto>? OssVatRates = null,
    [property: JsonPropertyName("pkwiu")]
    string? Pkwiu = null,
    [property: JsonPropertyName("price")]
    List<PriceDto>? Price = null,
    [property: JsonPropertyName("subjectToSplitPayment")]
    bool? SubjectToSplitPayment = null,
    [property: JsonPropertyName("symbol")]
    string? Symbol = null
);

public record CreateProductResultDto(
    [property: JsonPropertyName("id")]
    ProductExternalId? Id = null
);

public record DocumentBankAccountDto(
    [property: JsonPropertyName("name")]
    string? Name = null,
    [property: JsonPropertyName("number")]
    string? Number = null
);

public record DocumentClientDto(
    [property: JsonPropertyName("name")]
    string Name,
    [property: JsonPropertyName("address")]
    AddressDto? Address = null,
    [property: JsonPropertyName("kind")]
    DocumentClientKind? Kind = null,
    [property: JsonPropertyName("sourceClientId")]
    Guid? SourceClientId = null,
    [property: JsonPropertyName("tin")]
    string? Tin = null,
    [property: JsonPropertyName("tinKind")]
    TinKind? TinKind = null
);

public record DocumentCreateClientDto(
    [property: JsonPropertyName("address")]
    AddressDto? Address = null,
    [property: JsonPropertyName("kind")]
    DocumentClientKind? Kind = null,
    [property: JsonPropertyName("name")]
    string? Name = null,
    [property: JsonPropertyName("sourceClientId")]
    Guid? SourceClientId = null,
    [property: JsonPropertyName("tin")]
    string? Tin = null,
    [property: JsonPropertyName("tinKind")]
    TinKind? TinKind = null
);

public record DocumentDto(
    [property: JsonPropertyName("bankAccount")]
    DocumentBankAccountDto? BankAccount = null,
    [property: JsonPropertyName("bankAccountPln")]
    DocumentBankAccountDto? BankAccountPln = null,
    [property: JsonPropertyName("buyer")]
    DocumentClientDto? Buyer = null,
    [property: JsonPropertyName("calculationMethod")]
    CalculationMethod? CalculationMethod = null,
    [property: JsonPropertyName("cashBasis")]
    bool? CashBasis = null,
    [property: JsonPropertyName("client")]
    DocumentClientDto? Client = null,
    [property: JsonPropertyName("communityTransaction")]
    CommunityTransaction? CommunityTransaction = null,
    [property: JsonPropertyName("currency")]
    string? Currency = null,
    [property: JsonPropertyName("customVatReleaseReason")]
    string? CustomVatReleaseReason = null,
    [property: JsonPropertyName("deliveryAddress")]
    AddressDto? DeliveryAddress = null,
    [property: JsonPropertyName("deliveryDate")]
    DateTime? DeliveryDate = null,
    [property: JsonPropertyName("documentNumber")]
    string? DocumentNumber = null,
    [property: JsonPropertyName("dueDate")]
    DateTime? DueDate = null,
    [property: JsonPropertyName("dueDateDescription")]
    string? DueDateDescription = null,
    [property: JsonPropertyName("exchangeRate")]
    ExchangeRateDto? ExchangeRate = null,
    [property: JsonPropertyName("id")]
    Guid? Id = null,
    [property: JsonPropertyName("invoiceMode")]
    InvoiceMode? InvoiceMode = null,
    [property: JsonPropertyName("issueDate")]
    DateTime? IssueDate = null,
    [property: JsonPropertyName("issuedByVatPayer")]
    bool? IssuedByVatPayer = null,
    [property: JsonPropertyName("issuer")]
    string? Issuer = null,
    [property: JsonPropertyName("items")]
    List<DocumentItemDto>? Items = null,
    [property: JsonPropertyName("jpkVatGroups")]
    List<string>? JpkVatGroups = null,
    [property: JsonPropertyName("kind")]
    DocumentKind? Kind = null,
    [property: JsonPropertyName("ksefNumber")]
    string? KsefNumber = null,
    [property: JsonPropertyName("lastModificationDate")]
    DateTime? LastModificationDate = null,
    [property: JsonPropertyName("leftToPay")]
    decimal? LeftToPay = null,
    [property: JsonPropertyName("note")]
    string? Note = null,
    [property: JsonPropertyName("orderDate")]
    DateTime? OrderDate = null,
    [property: JsonPropertyName("paymentMethod")]
    PaymentMethod? PaymentMethod = null,
    [property: JsonPropertyName("payments")]
    List<PaymentDto>? Payments = null,
    [property: JsonPropertyName("paymentState")]
    PaymentState? PaymentState = null,
    [property: JsonPropertyName("recipient")]
    string? Recipient = null,
    [property: JsonPropertyName("seller")]
    SellerDto? Seller = null,
    [property: JsonPropertyName("splitPayment")]
    SplitPayment? SplitPayment = null,
    [property: JsonPropertyName("supplier")]
    SellerDto? Supplier = null,
    [property: JsonPropertyName("taxLiabilityDate")]
    DateTime? TaxLiabilityDate = null,
    [property: JsonPropertyName("totalGross")]
    decimal? TotalGross = null,
    [property: JsonPropertyName("totalGrossPln")]
    decimal? TotalGrossPln = null,
    [property: JsonPropertyName("totalNet")]
    decimal? TotalNet = null,
    [property: JsonPropertyName("totalNetPln")]
    decimal? TotalNetPln = null,
    [property: JsonPropertyName("transactionLocation")]
    string? TransactionLocation = null,
    [property: JsonPropertyName("vatReleaseReason")]
    VatReleaseReason? VatReleaseReason = null,
    [property: JsonPropertyName("vatTableItems")]
    List<VatTableItemDto>? VatTableItems = null,
    [property: JsonPropertyName("wstoAdditionalInformation")]
    string? WstoAdditionalInformation = null,
    [property: JsonPropertyName("wstoConsumerCountry")]
    string? WstoConsumerCountry = null,
    [property: JsonPropertyName("wstoShipmentCountry")]
    string? WstoShipmentCountry = null
);

public record DocumentExternalId(
    [property: JsonPropertyName("value")]
    Guid? Value = null
);

public record DocumentItemDto(
    [property: JsonPropertyName("barcode")]
    string? Barcode = null,
    [property: JsonPropertyName("cnCode")]
    string? CnCode = null,
    [property: JsonPropertyName("discount")]
    decimal? Discount = null,
    [property: JsonPropertyName("discountKind")]
    DiscountKind? DiscountKind = null,
    [property: JsonPropertyName("grossPrice")]
    decimal? GrossPrice = null,
    [property: JsonPropertyName("grossPriceAfterDiscount")]
    decimal? GrossPriceAfterDiscount = null,
    [property: JsonPropertyName("grossValue")]
    decimal? GrossValue = null,
    [property: JsonPropertyName("grossValueAfterDiscount")]
    decimal? GrossValueAfterDiscount = null,
    [property: JsonPropertyName("gtu")]
    string? Gtu = null,
    [property: JsonPropertyName("netPrice")]
    decimal? NetPrice = null,
    [property: JsonPropertyName("netPriceAfterDiscount")]
    decimal? NetPriceAfterDiscount = null,
    [property: JsonPropertyName("netValue")]
    decimal? NetValue = null,
    [property: JsonPropertyName("netValueAfterDiscount")]
    decimal? NetValueAfterDiscount = null,
    [property: JsonPropertyName("no")]
    int? No = null,
    [property: JsonPropertyName("note")]
    string? Note = null,
    [property: JsonPropertyName("pkwiu")]
    string? Pkwiu = null,
    [property: JsonPropertyName("productName")]
    string? ProductName = null,
    [property: JsonPropertyName("quantity")]
    decimal? Quantity = null,
    [property: JsonPropertyName("sourceProductId")]
    int? SourceProductId = null,
    [property: JsonPropertyName("symbol")]
    string? Symbol = null,
    [property: JsonPropertyName("unit")]
    string? Unit = null,
    [property: JsonPropertyName("vatRate")]
    string? VatRate = null
);

public record DocumentListDto(
    [property: JsonPropertyName("buyer")]
    string? Buyer = null,
    [property: JsonPropertyName("calculationMethod")]
    CalculationMethod? CalculationMethod = null,
    [property: JsonPropertyName("client")]
    string? Client = null,
    [property: JsonPropertyName("clientAddress")]
    AddressDto? ClientAddress = null,
    [property: JsonPropertyName("clientTin")]
    string? ClientTin = null,
    [property: JsonPropertyName("currency")]
    string? Currency = null,
    [property: JsonPropertyName("deliveryDate")]
    DateTime? DeliveryDate = null,
    [property: JsonPropertyName("documentNumber")]
    string? DocumentNumber = null,
    [property: JsonPropertyName("dueDate")]
    DateTime? DueDate = null,
    [property: JsonPropertyName("id")]
    Guid? Id = null,
    [property: JsonPropertyName("invoiceMode")]
    InvoiceMode? InvoiceMode = null,
    [property: JsonPropertyName("issueDate")]
    DateTime? IssueDate = null,
    [property: JsonPropertyName("issuer")]
    string? Issuer = null,
    [property: JsonPropertyName("kind")]
    DocumentKind? Kind = null,
    [property: JsonPropertyName("ksefNumber")]
    string? KsefNumber = null,
    [property: JsonPropertyName("lastModificationDate")]
    DateTime? LastModificationDate = null,
    [property: JsonPropertyName("leftToPay")]
    decimal? LeftToPay = null,
    [property: JsonPropertyName("paymentState")]
    PaymentState? PaymentState = null,
    [property: JsonPropertyName("taxLiabilityDate")]
    DateTime? TaxLiabilityDate = null,
    [property: JsonPropertyName("totalGross")]
    decimal? TotalGross = null,
    [property: JsonPropertyName("totalGrossPln")]
    decimal? TotalGrossPln = null,
    [property: JsonPropertyName("totalNet")]
    decimal? TotalNet = null,
    [property: JsonPropertyName("totalNetPln")]
    decimal? TotalNetPln = null,
    [property: JsonPropertyName("transactionLocation")]
    string? TransactionLocation = null
);

public record DocumentPrintingSettingsDto(
    [property: JsonPropertyName("duplicateDate")]
    DateTime? DuplicateDate = null,
    [property: JsonPropertyName("ecoMode")]
    bool? EcoMode = null
);

public record ErrorDescription(
    [property: JsonPropertyName("code")]
    string? Code = null,
    [property: JsonPropertyName("message")]
    string? Message = null
);

public record ExchangeRateDto(
    [property: JsonPropertyName("date")]
    DateTime? Date = null,
    [property: JsonPropertyName("rate")]
    decimal? Rate = null,
    [property: JsonPropertyName("tableNo")]
    string? TableNo = null,
    [property: JsonPropertyName("unit")]
    int? Unit = null
);

public record ExtendedClientDto(
    [property: JsonPropertyName("address")]
    AddressDto? Address = null,
    [property: JsonPropertyName("associatedClient")]
    bool? AssociatedClient = null,
    [property: JsonPropertyName("bankAccounts")]
    List<ClientBankAccountDto>? BankAccounts = null,
    [property: JsonPropertyName("buyerId")]
    Guid? BuyerId = null,
    [property: JsonPropertyName("defaultDiscount")]
    decimal? DefaultDiscount = null,
    [property: JsonPropertyName("defaultDueDate")]
    int? DefaultDueDate = null,
    [property: JsonPropertyName("defaultPaymentMethod")]
    PaymentMethod? DefaultPaymentMethod = null,
    [property: JsonPropertyName("deliveryAddress")]
    AddressDto? DeliveryAddress = null,
    [property: JsonPropertyName("emails")]
    List<string>? Emails = null,
    [property: JsonPropertyName("favourite")]
    bool? Favourite = null,
    [property: JsonPropertyName("group")]
    string? Group = null,
    [property: JsonPropertyName("id")]
    Guid? Id = null,
    [property: JsonPropertyName("kind")]
    ClientKind? Kind = null,
    [property: JsonPropertyName("name")]
    string? Name = null,
    [property: JsonPropertyName("note")]
    string? Note = null,
    [property: JsonPropertyName("phone1")]
    string? Phone1 = null,
    [property: JsonPropertyName("phone2")]
    string? Phone2 = null,
    [property: JsonPropertyName("skype")]
    string? Skype = null,
    [property: JsonPropertyName("tin")]
    string? Tin = null,
    [property: JsonPropertyName("tinKind")]
    TinKind? TinKind = null,
    [property: JsonPropertyName("website")]
    string? Website = null
);

public record ExtendedDocumentDto(
    [property: JsonPropertyName("bankAccount")]
    DocumentBankAccountDto? BankAccount = null,
    [property: JsonPropertyName("bankAccountPln")]
    DocumentBankAccountDto? BankAccountPln = null,
    [property: JsonPropertyName("buyer")]
    DocumentClientDto? Buyer = null,
    [property: JsonPropertyName("calculationMethod")]
    CalculationMethod? CalculationMethod = null,
    [property: JsonPropertyName("cashBasis")]
    bool? CashBasis = null,
    [property: JsonPropertyName("client")]
    DocumentClientDto? Client = null,
    [property: JsonPropertyName("communityTransaction")]
    CommunityTransaction? CommunityTransaction = null,
    [property: JsonPropertyName("currency")]
    string? Currency = null,
    [property: JsonPropertyName("customVatReleaseReason")]
    string? CustomVatReleaseReason = null,
    [property: JsonPropertyName("deliveryAddress")]
    AddressDto? DeliveryAddress = null,
    [property: JsonPropertyName("deliveryDate")]
    DateTime? DeliveryDate = null,
    [property: JsonPropertyName("documentNumber")]
    string? DocumentNumber = null,
    [property: JsonPropertyName("dueDate")]
    DateTime? DueDate = null,
    [property: JsonPropertyName("dueDateDescription")]
    string? DueDateDescription = null,
    [property: JsonPropertyName("exchangeRate")]
    ExchangeRateDto? ExchangeRate = null,
    [property: JsonPropertyName("id")]
    Guid? Id = null,
    [property: JsonPropertyName("invoiceMode")]
    InvoiceMode? InvoiceMode = null,
    [property: JsonPropertyName("issueDate")]
    DateTime? IssueDate = null,
    [property: JsonPropertyName("issuedByVatPayer")]
    bool? IssuedByVatPayer = null,
    [property: JsonPropertyName("issuer")]
    string? Issuer = null,
    [property: JsonPropertyName("items")]
    List<ExtendedDocumentItemDto>? Items = null,
    [property: JsonPropertyName("jpkVatGroups")]
    List<string>? JpkVatGroups = null,
    [property: JsonPropertyName("kind")]
    DocumentKind? Kind = null,
    [property: JsonPropertyName("ksefNumber")]
    string? KsefNumber = null,
    [property: JsonPropertyName("lastModificationDate")]
    DateTime? LastModificationDate = null,
    [property: JsonPropertyName("leftToPay")]
    decimal? LeftToPay = null,
    [property: JsonPropertyName("note")]
    string? Note = null,
    [property: JsonPropertyName("orderDate")]
    DateTime? OrderDate = null,
    [property: JsonPropertyName("paymentMethod")]
    PaymentMethod? PaymentMethod = null,
    [property: JsonPropertyName("payments")]
    List<PaymentDto>? Payments = null,
    [property: JsonPropertyName("paymentState")]
    PaymentState? PaymentState = null,
    [property: JsonPropertyName("recipient")]
    string? Recipient = null,
    [property: JsonPropertyName("seller")]
    SellerDto? Seller = null,
    [property: JsonPropertyName("splitPayment")]
    SplitPayment? SplitPayment = null,
    [property: JsonPropertyName("supplier")]
    SellerDto? Supplier = null,
    [property: JsonPropertyName("taxLiabilityDate")]
    DateTime? TaxLiabilityDate = null,
    [property: JsonPropertyName("totalGross")]
    decimal? TotalGross = null,
    [property: JsonPropertyName("totalGrossPln")]
    decimal? TotalGrossPln = null,
    [property: JsonPropertyName("totalNet")]
    decimal? TotalNet = null,
    [property: JsonPropertyName("totalNetPln")]
    decimal? TotalNetPln = null,
    [property: JsonPropertyName("transactionLocation")]
    string? TransactionLocation = null,
    [property: JsonPropertyName("vatReleaseReason")]
    VatReleaseReason? VatReleaseReason = null,
    [property: JsonPropertyName("vatTableItems")]
    List<ExtendedVatTableItemDto>? VatTableItems = null,
    [property: JsonPropertyName("wstoAdditionalInformation")]
    string? WstoAdditionalInformation = null,
    [property: JsonPropertyName("wstoConsumerCountry")]
    string? WstoConsumerCountry = null,
    [property: JsonPropertyName("wstoShipmentCountry")]
    string? WstoShipmentCountry = null
);

public record ExtendedDocumentItemDto(
    [property: JsonPropertyName("cnCode")]
    string? CnCode = null,
    [property: JsonPropertyName("discount")]
    decimal? Discount = null,
    [property: JsonPropertyName("discountKind")]
    DiscountKind? DiscountKind = null,
    [property: JsonPropertyName("grossPrice")]
    decimal? GrossPrice = null,
    [property: JsonPropertyName("grossPriceAfterDiscount")]
    decimal? GrossPriceAfterDiscount = null,
    [property: JsonPropertyName("grossValue")]
    decimal? GrossValue = null,
    [property: JsonPropertyName("grossValueAfterDiscount")]
    decimal? GrossValueAfterDiscount = null,
    [property: JsonPropertyName("gtu")]
    string? Gtu = null,
    [property: JsonPropertyName("netPrice")]
    decimal? NetPrice = null,
    [property: JsonPropertyName("netPriceAfterDiscount")]
    decimal? NetPriceAfterDiscount = null,
    [property: JsonPropertyName("netValue")]
    decimal? NetValue = null,
    [property: JsonPropertyName("netValueAfterDiscount")]
    decimal? NetValueAfterDiscount = null,
    [property: JsonPropertyName("no")]
    int? No = null,
    [property: JsonPropertyName("note")]
    string? Note = null,
    [property: JsonPropertyName("pkwiu")]
    string? Pkwiu = null,
    [property: JsonPropertyName("productName")]
    string? ProductName = null,
    [property: JsonPropertyName("quantity")]
    decimal? Quantity = null,
    [property: JsonPropertyName("sourceProductId")]
    int? SourceProductId = null,
    [property: JsonPropertyName("unit")]
    string? Unit = null,
    [property: JsonPropertyName("vatRate")]
    string? VatRate = null
);

public record ExtendedProductDto(
    [property: JsonPropertyName("barcode")]
    string? Barcode = null,
    [property: JsonPropertyName("cnCode")]
    string? CnCode = null,
    [property: JsonPropertyName("description")]
    string? Description = null,
    [property: JsonPropertyName("favourite")]
    bool? Favourite = null,
    [property: JsonPropertyName("fiscalName")]
    string? FiscalName = null,
    [property: JsonPropertyName("group")]
    string? Group = null,
    [property: JsonPropertyName("id")]
    Guid? Id = null,
    [property: JsonPropertyName("jpkVatGroups")]
    List<string>? JpkVatGroups = null,
    [property: JsonPropertyName("kind")]
    ProductKind? Kind = null,
    [property: JsonPropertyName("name")]
    string? Name = null,
    [property: JsonPropertyName("ossVatRates")]
    List<OssVatRateDto>? OssVatRates = null,
    [property: JsonPropertyName("pkwiu")]
    string? Pkwiu = null,
    [property: JsonPropertyName("price")]
    List<PriceDto>? Price = null,
    [property: JsonPropertyName("subjectToSplitPayment")]
    bool? SubjectToSplitPayment = null,
    [property: JsonPropertyName("symbol")]
    string? Symbol = null,
    [property: JsonPropertyName("unit")]
    string? Unit = null,
    [property: JsonPropertyName("vatRate")]
    string? VatRate = null
);

public record ExtendedVatTableItemDto(
    [property: JsonPropertyName("gross")]
    decimal? Gross = null,
    [property: JsonPropertyName("grossPln")]
    decimal? GrossPln = null,
    [property: JsonPropertyName("net")]
    decimal? Net = null,
    [property: JsonPropertyName("netPln")]
    decimal? NetPln = null,
    [property: JsonPropertyName("vat")]
    decimal? Vat = null,
    [property: JsonPropertyName("vatPln")]
    decimal? VatPln = null,
    [property: JsonPropertyName("vatRate")]
    string? VatRate = null
);

public record OssVatRateDto(
    [property: JsonPropertyName("country")]
    string Country,
    [property: JsonPropertyName("vatRate")]
    string VatRate
);

public record PaymentDto(
    [property: JsonPropertyName("date")]
    DateTime? Date = null,
    [property: JsonPropertyName("onDocument")]
    bool? OnDocument = null,
    [property: JsonPropertyName("value")]
    decimal? Value = null
);

public record PriceDto(
    [property: JsonPropertyName("currency")]
    string Currency,
    [property: JsonPropertyName("gross")]
    decimal? Gross = null,
    [property: JsonPropertyName("net")]
    decimal? Net = null
);

public record ProductDto(
    [property: JsonPropertyName("barcode")]
    string? Barcode = null,
    [property: JsonPropertyName("cnCode")]
    string? CnCode = null,
    [property: JsonPropertyName("description")]
    string? Description = null,
    [property: JsonPropertyName("favourite")]
    bool? Favourite = null,
    [property: JsonPropertyName("fiscalName")]
    string? FiscalName = null,
    [property: JsonPropertyName("group")]
    string? Group = null,
    [property: JsonPropertyName("id")]
    Guid? Id = null,
    [property: JsonPropertyName("jpkVatGroups")]
    List<string>? JpkVatGroups = null,
    [property: JsonPropertyName("kind")]
    ProductKind? Kind = null,
    [property: JsonPropertyName("name")]
    string? Name = null,
    [property: JsonPropertyName("ossVatRates")]
    List<OssVatRateDto>? OssVatRates = null,
    [property: JsonPropertyName("pkwiu")]
    string? Pkwiu = null,
    [property: JsonPropertyName("price")]
    List<PriceDto>? Price = null,
    [property: JsonPropertyName("subjectToSplitPayment")]
    bool? SubjectToSplitPayment = null,
    [property: JsonPropertyName("symbol")]
    string? Symbol = null,
    [property: JsonPropertyName("unit")]
    string? Unit = null,
    [property: JsonPropertyName("vatRate")]
    string? VatRate = null
);

public record ProductExternalId(
    [property: JsonPropertyName("value")]
    Guid? Value = null
);

public record ProductListItemDto(
    [property: JsonPropertyName("barcode")]
    string? Barcode = null,
    [property: JsonPropertyName("cnCode")]
    string? CnCode = null,
    [property: JsonPropertyName("currency")]
    string? Currency = null,
    [property: JsonPropertyName("description")]
    string? Description = null,
    [property: JsonPropertyName("favourite")]
    bool? Favourite = null,
    [property: JsonPropertyName("fiscalName")]
    string? FiscalName = null,
    [property: JsonPropertyName("grossPrice")]
    decimal? GrossPrice = null,
    [property: JsonPropertyName("group")]
    string? Group = null,
    [property: JsonPropertyName("id")]
    Guid? Id = null,
    [property: JsonPropertyName("jpkVatGroups")]
    List<string>? JpkVatGroups = null,
    [property: JsonPropertyName("kind")]
    ProductKind? Kind = null,
    [property: JsonPropertyName("name")]
    string? Name = null,
    [property: JsonPropertyName("netPrice")]
    decimal? NetPrice = null,
    [property: JsonPropertyName("pkwiu")]
    string? Pkwiu = null,
    [property: JsonPropertyName("subjectToSplitPayment")]
    bool? SubjectToSplitPayment = null,
    [property: JsonPropertyName("symbol")]
    string? Symbol = null,
    [property: JsonPropertyName("unit")]
    string? Unit = null,
    [property: JsonPropertyName("vatRate")]
    string? VatRate = null
);

public record PropertyErrorDescription(
    [property: JsonPropertyName("code")]
    string? Code = null,
    [property: JsonPropertyName("message")]
    string? Message = null,
    [property: JsonPropertyName("path")]
    string? Path = null
);

public record SellerDto(
    [property: JsonPropertyName("address")]
    AddressDto? Address = null,
    [property: JsonPropertyName("kind")]
    SellerKind? Kind = null,
    [property: JsonPropertyName("name")]
    string? Name = null,
    [property: JsonPropertyName("tin")]
    string? Tin = null,
    [property: JsonPropertyName("tinKind")]
    TinKind? TinKind = null
);

public record UpdateClientDto(
    [property: JsonPropertyName("name")]
    string Name,
    [property: JsonPropertyName("address")]
    AddressDto? Address = null,
    [property: JsonPropertyName("associatedClient")]
    bool? AssociatedClient = null,
    [property: JsonPropertyName("bankAccounts")]
    List<ClientBankAccountDto>? BankAccounts = null,
    [property: JsonPropertyName("buyerId")]
    Guid? BuyerId = null,
    [property: JsonPropertyName("defaultDiscount")]
    decimal? DefaultDiscount = null,
    [property: JsonPropertyName("defaultDueDate")]
    int? DefaultDueDate = null,
    [property: JsonPropertyName("defaultPaymentMethod")]
    PaymentMethod? DefaultPaymentMethod = null,
    [property: JsonPropertyName("deliveryAddress")]
    AddressDto? DeliveryAddress = null,
    [property: JsonPropertyName("emails")]
    List<string>? Emails = null,
    [property: JsonPropertyName("favourite")]
    bool? Favourite = null,
    [property: JsonPropertyName("group")]
    string? Group = null,
    [property: JsonPropertyName("kind")]
    ClientKind? Kind = null,
    [property: JsonPropertyName("note")]
    string? Note = null,
    [property: JsonPropertyName("phone1")]
    string? Phone1 = null,
    [property: JsonPropertyName("phone2")]
    string? Phone2 = null,
    [property: JsonPropertyName("skype")]
    string? Skype = null,
    [property: JsonPropertyName("tin")]
    string? Tin = null,
    [property: JsonPropertyName("tinKind")]
    TinKind? TinKind = null,
    [property: JsonPropertyName("website")]
    string? Website = null
);

public record UpdateClientResultDto(
    [property: JsonPropertyName("id")]
    ClientExternalId? Id = null
);

public record UpdateDocumentDto(
    [property: JsonPropertyName("currency")]
    string Currency,
    [property: JsonPropertyName("issuer")]
    string Issuer,
    [property: JsonPropertyName("bankAccount")]
    DocumentBankAccountDto? BankAccount = null,
    [property: JsonPropertyName("bankAccountPln")]
    DocumentBankAccountDto? BankAccountPln = null,
    [property: JsonPropertyName("buyer")]
    DocumentClientDto? Buyer = null,
    [property: JsonPropertyName("calculationMethod")]
    CalculationMethod? CalculationMethod = null,
    [property: JsonPropertyName("cashBasis")]
    bool? CashBasis = null,
    [property: JsonPropertyName("client")]
    DocumentClientDto? Client = null,
    [property: JsonPropertyName("communityTransaction")]
    CommunityTransaction? CommunityTransaction = null,
    [property: JsonPropertyName("customVatReleaseReason")]
    string? CustomVatReleaseReason = null,
    [property: JsonPropertyName("deliveryAddress")]
    AddressDto? DeliveryAddress = null,
    [property: JsonPropertyName("deliveryDate")]
    DateTime? DeliveryDate = null,
    [property: JsonPropertyName("dueDate")]
    DateTime? DueDate = null,
    [property: JsonPropertyName("dueDateDescription")]
    string? DueDateDescription = null,
    [property: JsonPropertyName("eInvoice")]
    bool? EInvoice = null,
    [property: JsonPropertyName("exchangeRate")]
    ExchangeRateDto? ExchangeRate = null,
    [property: JsonPropertyName("issueDate")]
    DateTime? IssueDate = null,
    [property: JsonPropertyName("items")]
    List<CreateDocumentItemDto>? Items = null,
    [property: JsonPropertyName("jpkVatGroups")]
    List<string>? JpkVatGroups = null,
    [property: JsonPropertyName("kind")]
    DocumentKind? Kind = null,
    [property: JsonPropertyName("note")]
    string? Note = null,
    [property: JsonPropertyName("orderDate")]
    DateTime? OrderDate = null,
    [property: JsonPropertyName("paymentMethod")]
    PaymentMethod? PaymentMethod = null,
    [property: JsonPropertyName("payments")]
    List<PaymentDto>? Payments = null,
    [property: JsonPropertyName("recipient")]
    string? Recipient = null,
    [property: JsonPropertyName("splitPayment")]
    SplitPayment? SplitPayment = null,
    [property: JsonPropertyName("taxLiabilityDate")]
    DateTime? TaxLiabilityDate = null,
    [property: JsonPropertyName("transactionLocation")]
    string? TransactionLocation = null,
    [property: JsonPropertyName("vatReleaseReason")]
    VatReleaseReason? VatReleaseReason = null,
    [property: JsonPropertyName("wstoAdditionalInformation")]
    string? WstoAdditionalInformation = null,
    [property: JsonPropertyName("wstoConsumerCountry")]
    string? WstoConsumerCountry = null,
    [property: JsonPropertyName("wstoShipmentCountry")]
    string? WstoShipmentCountry = null
);

public record UpdateDocumentResultDto(
    [property: JsonPropertyName("id")]
    DocumentExternalId? Id = null
);

public record UpdateProductDto(
    [property: JsonPropertyName("name")]
    string Name,
    [property: JsonPropertyName("unit")]
    string Unit,
    [property: JsonPropertyName("vatRate")]
    string VatRate,
    [property: JsonPropertyName("barcode")]
    string? Barcode = null,
    [property: JsonPropertyName("cnCode")]
    string? CnCode = null,
    [property: JsonPropertyName("description")]
    string? Description = null,
    [property: JsonPropertyName("favourite")]
    bool? Favourite = null,
    [property: JsonPropertyName("fiscalName")]
    string? FiscalName = null,
    [property: JsonPropertyName("group")]
    string? Group = null,
    [property: JsonPropertyName("jpkVatGroups")]
    List<string>? JpkVatGroups = null,
    [property: JsonPropertyName("ossVatRates")]
    List<OssVatRateDto>? OssVatRates = null,
    [property: JsonPropertyName("pkwiu")]
    string? Pkwiu = null,
    [property: JsonPropertyName("price")]
    List<PriceDto>? Price = null,
    [property: JsonPropertyName("subjectToSplitPayment")]
    bool? SubjectToSplitPayment = null,
    [property: JsonPropertyName("symbol")]
    string? Symbol = null
);

public record UpdateProductResultDto(
    [property: JsonPropertyName("id")]
    ProductExternalId? Id = null
);

public record VatTableItemDto(
    [property: JsonPropertyName("gross")]
    decimal? Gross = null,
    [property: JsonPropertyName("grossPln")]
    decimal? GrossPln = null,
    [property: JsonPropertyName("net")]
    decimal? Net = null,
    [property: JsonPropertyName("netPln")]
    decimal? NetPln = null,
    [property: JsonPropertyName("vat")]
    decimal? Vat = null,
    [property: JsonPropertyName("vatPln")]
    decimal? VatPln = null,
    [property: JsonPropertyName("vatRate")]
    string? VatRate = null
);

