// <auto-generated/>
// Generated from src/openapi.json (Subiekt 123 API v1.1)
// Do not edit manually — regenerate via: dotnet run --project tools/ContractGenerator

#nullable enable

using Subiekt.Connector.Contracts;

namespace Subiekt.Connector.Sdk;

public partial class ClientsResource
{
    private readonly SubiektClient _client;
    internal ClientsResource(SubiektClient client) => _client = client;

    public Task<ClientDto> GetAsync(Guid id, CancellationToken ct = default)
        => _client.GetAsync<ClientDto>($"clients/{id}", ct);

    public Task<UpdateClientResultDto> UpdateAsync(Guid id, UpdateClientDto dto, string etag, CancellationToken ct = default)
        => _client.PutAsync<UpdateClientResultDto>($"clients/{id}", dto, etag, ct);

    public Task DeleteAsync(Guid id, CancellationToken ct = default)
        => _client.DeleteAsync($"clients/{id}", ct);

    public Task<PagedResult<ClientListItemDto>> ListAsync(
        int pageNumber = 0, int pageSize = 25,
        string[]? filters = null, string[]? orderBy = null,
        CancellationToken ct = default)
        => _client.GetListAsync<ClientListItemDto>(
            $"clients{SubiektClient.BuildListQuery(pageNumber, pageSize, filters, orderBy)}", ct);

    public Task<CreateClientResultDto> CreateAsync(CreateClientDto dto, CancellationToken ct = default)
        => _client.PostAsync<CreateClientResultDto>("clients", dto, ct);
}

public partial class DocumentsResource
{
    private readonly SubiektClient _client;
    internal DocumentsResource(SubiektClient client) => _client = client;

    public Task<DocumentDto> GetAsync(Guid id, CancellationToken ct = default)
        => _client.GetAsync<DocumentDto>($"documents/{id}", ct);

    public Task<UpdateDocumentResultDto> UpdateAsync(Guid id, UpdateDocumentDto dto, string etag, CancellationToken ct = default)
        => _client.PutAsync<UpdateDocumentResultDto>($"documents/{id}", dto, etag, ct);

    public Task DeleteAsync(Guid id, CancellationToken ct = default)
        => _client.DeleteAsync($"documents/{id}", ct);

    public Task<PagedResult<DocumentListDto>> ListAsync(
        int pageNumber = 0, int pageSize = 25,
        string[]? filters = null, string[]? orderBy = null,
        CancellationToken ct = default)
        => _client.GetListAsync<DocumentListDto>(
            $"documents{SubiektClient.BuildListQuery(pageNumber, pageSize, filters, orderBy)}", ct);

    public Task<CreateDocumentResultDto> CreateAsync(CreateDocumentDto dto, CancellationToken ct = default)
        => _client.PostAsync<CreateDocumentResultDto>("documents", dto, ct);

    public Task<byte[]> PrintAsync(Guid id, DocumentPrintingSettingsDto settings, CancellationToken ct = default)
        => _client.PostBytesAsync($"documents/{id}/printing", settings, ct);
}

public partial class ProductsResource
{
    private readonly SubiektClient _client;
    internal ProductsResource(SubiektClient client) => _client = client;

    public Task<ProductDto> GetAsync(Guid id, CancellationToken ct = default)
        => _client.GetAsync<ProductDto>($"products/{id}", ct);

    public Task<UpdateProductResultDto> UpdateAsync(Guid id, UpdateProductDto dto, string etag, CancellationToken ct = default)
        => _client.PutAsync<UpdateProductResultDto>($"products/{id}", dto, etag, ct);

    public Task<PagedResult<ProductListItemDto>> ListAsync(
        int pageNumber = 0, int pageSize = 25,
        string[]? filters = null, string[]? orderBy = null,
        CancellationToken ct = default)
        => _client.GetListAsync<ProductListItemDto>(
            $"products{SubiektClient.BuildListQuery(pageNumber, pageSize, filters, orderBy)}", ct);

    public Task<CreateProductResultDto> CreateAsync(CreateProductDto dto, CancellationToken ct = default)
        => _client.PostAsync<CreateProductResultDto>("products", dto, ct);

    public Task DeactivateAsync(Guid id, CancellationToken ct = default)
        => _client.PatchAsync($"products/{id}/deactivate", ct);
}

