using System.Text;
using System.Text.Json;

// ---------- resolve paths relative to this tool's location ----------
var repoRoot = FindRepoRoot(AppContext.BaseDirectory)
    ?? throw new InvalidOperationException("Could not find repository root (looked for src/openapi.json)");
var openApiPath = Path.Combine(repoRoot, "src", "openapi.json");
var outputPath = Path.Combine(repoRoot, "src", "Subiekt.Connector.Contracts", "Contracts.cs");

Console.WriteLine($"[ContractGenerator] Reading {openApiPath}");
var rootArray = JsonSerializer.Deserialize<JsonElement>(File.ReadAllText(openApiPath));

// find the v1.1 entry
JsonElement? specElement = null;
foreach (var entry in rootArray.EnumerateArray())
{
    if (entry.GetProperty("Version").GetString() == "1.1")
    {
        specElement = JsonSerializer.Deserialize<JsonElement>(entry.GetProperty("OpenApi").GetString()!);
        break;
    }
}
if (specElement is null)
    throw new InvalidOperationException("Version 1.1 not found in openapi.json");

var schemas = specElement.Value.GetProperty("components").GetProperty("schemas");

// ---------- build name mapping ----------
var nameMap = BuildNameMap(schemas);

// ---------- generate code ----------
var sb = new StringBuilder();
sb.AppendLine("// <auto-generated/>");
sb.AppendLine("// Generated from src/openapi.json (Subiekt 123 API v1.1)");
sb.AppendLine("// Do not edit manually — regenerate via: dotnet run --project tools/ContractGenerator");
sb.AppendLine();
sb.AppendLine("#nullable enable");
sb.AppendLine();
sb.AppendLine("using System.Text.Json.Serialization;");
sb.AppendLine();
sb.AppendLine("[assembly: System.Runtime.CompilerServices.InternalsVisibleTo(\"Subiekt.Connector.IntegrationTests\")]");
sb.AppendLine();
sb.AppendLine("namespace Subiekt.Connector.Contracts;");
sb.AppendLine();

// PagedResult<T> — the API returns { items: [...], totalItems: N } for list endpoints
sb.AppendLine("/// <summary>Paged response wrapper for list endpoints.</summary>");
sb.AppendLine("public record PagedResult<T>(");
sb.AppendLine("    [property: JsonPropertyName(\"items\")] List<T>? Items,");
sb.AppendLine("    [property: JsonPropertyName(\"totalItemsCount\")] int TotalItemsCount");
sb.AppendLine(");");
sb.AppendLine();

// enums first, then records
var enums = new List<(string csName, string fullName)>();
var records = new List<(string csName, string fullName)>();

foreach (var kv in nameMap.OrderBy(x => x.Value))
{
    var schema = schemas.GetProperty(kv.Key);
    if (schema.TryGetProperty("enum", out _))
        enums.Add((kv.Value, kv.Key));
    else
        records.Add((kv.Value, kv.Key));
}

foreach (var (csName, fullName) in enums)
    GenerateEnum(sb, csName, schemas.GetProperty(fullName));

foreach (var (csName, fullName) in records)
    GenerateRecord(sb, csName, schemas.GetProperty(fullName), nameMap);

File.WriteAllText(outputPath, sb.ToString(), new UTF8Encoding(false));
Console.WriteLine($"[ContractGenerator] Generated {outputPath} ({enums.Count} enums, {records.Count} records)");

// ---------- generate resource classes from paths ----------
var resourcesPath = Path.Combine(repoRoot, "src", "Subiekt.Connector.Sdk", "Resources", "Resources.generated.cs");
var paths = specElement.Value.GetProperty("paths");
var resSb = GenerateResources(paths, nameMap);
File.WriteAllText(resourcesPath, resSb.ToString(), new UTF8Encoding(false));
Console.WriteLine($"[ContractGenerator] Generated {resourcesPath}");
return;

// ======================== helpers ========================

static string? FindRepoRoot(string start)
{
    var dir = start;
    for (int i = 0; i < 10; i++)
    {
        if (File.Exists(Path.Combine(dir, "src", "openapi.json")))
            return dir;
        var parent = Directory.GetParent(dir)?.FullName;
        if (parent is null || parent == dir) break;
        dir = parent;
    }
    return null;
}

static Dictionary<string, string> BuildNameMap(JsonElement schemas)
{
    var map = new Dictionary<string, string>();
    var shortNameCounts = new Dictionary<string, List<string>>();

    // First pass: group by short name to detect collisions
    foreach (var prop in schemas.EnumerateObject())
    {
        var shortName = prop.Name.Split('.').Last();
        if (!shortNameCounts.TryGetValue(shortName, out var list))
        {
            list = [];
            shortNameCounts[shortName] = list;
        }
        list.Add(prop.Name);
    }

    // Second pass: assign C# names
    foreach (var prop in schemas.EnumerateObject())
    {
        var fullName = prop.Name;
        var segments = fullName.Split('.');
        var shortName = segments.Last();
        var context = segments.Length >= 2 ? segments[^2] : "";
        var domain = ExtractDomain(fullName);

        if (shortNameCounts[shortName].Count == 1)
        {
            map[fullName] = shortName;
        }
        else
        {
            map[fullName] = DisambiguateName(shortName, context, domain);
        }
    }

    return map;
}

static string ExtractDomain(string fullName)
{
    if (fullName.Contains(".Clients.")) return "Client";
    if (fullName.Contains(".Documents.")) return "Document";
    if (fullName.Contains(".Products.")) return "Product";
    return "";
}

static string DisambiguateName(string shortName, string context, string domain)
{
    // GetExtendedXxxList.SomeDto → ExtendedSomeDto
    if (context.StartsWith("GetExtended"))
    {
        if (!shortName.StartsWith("Extended"))
            return "Extended" + shortName;
        return shortName;
    }

    // GetXxxList.SomeDto → list item variant
    if (context.StartsWith("Get") && context.Contains("List"))
    {
        var baseName = shortName.Replace("Dto", "");
        if (baseName == domain)
            return domain == "Document" ? baseName + "ListDto" : baseName + "ListItemDto";
        return baseName + "ListDto";
    }

    // GetXxxByExternalId / GetXxxById → canonical DTO (keep short name)
    if (context.StartsWith("Get") && (context.Contains("ById") || context.Contains("ByExternalId")))
        return shortName;

    // Shared types: prefix with domain to avoid collision
    if (context == "Shared")
    {
        // Special: Shared.DocumentItemDto → CreateDocumentItemDto (used in create/update requests)
        if (shortName == "DocumentItemDto")
            return "CreateDocumentItemDto";
        if (shortName.StartsWith(domain))
            return shortName;
        return domain + shortName;
    }

    // CreateDocument.ClientDto → DocumentCreateClientDto
    if (context.StartsWith("Create") && shortName == "ClientDto")
        return domain + "CreateClientDto";

    // Fallback: prefix with domain
    if (!shortName.StartsWith(domain))
        return domain + shortName;

    return shortName;
}

static void GenerateEnum(StringBuilder sb, string csName, JsonElement schema)
{
    sb.AppendLine("[JsonConverter(typeof(JsonStringEnumConverter))]");
    sb.AppendLine($"public enum {csName}");
    sb.AppendLine("{");
    foreach (var val in schema.GetProperty("enum").EnumerateArray())
        sb.AppendLine($"    {val.GetString()},");
    sb.AppendLine("}");
    sb.AppendLine();
}

static void GenerateRecord(StringBuilder sb, string csName, JsonElement schema,
    Dictionary<string, string> nameMap)
{
    if (!schema.TryGetProperty("properties", out var props))
    {
        sb.AppendLine($"public record {csName};");
        sb.AppendLine();
        return;
    }

    var required = new HashSet<string>();
    if (schema.TryGetProperty("required", out var reqArr))
        foreach (var r in reqArr.EnumerateArray())
            required.Add(r.GetString()!);

    var parameters = new List<(string jsonName, string csType, bool isRequired)>();
    foreach (var p in props.EnumerateObject())
    {
        var csType = ResolveCsType(p.Value, nameMap);
        parameters.Add((p.Name, csType, required.Contains(p.Name)));
    }

    // Required first (alphabetically), then optional (alphabetically)
    var sorted = parameters
        .OrderByDescending(p => p.isRequired)
        .ThenBy(p => p.jsonName)
        .ToList();

    sb.AppendLine($"public record {csName}(");
    for (int i = 0; i < sorted.Count; i++)
    {
        var (jsonName, csType, isReq) = sorted[i];
        var csParamName = ToPascalCase(jsonName);
        var comma = i < sorted.Count - 1 ? "," : "";

        sb.AppendLine($"    [property: JsonPropertyName(\"{jsonName}\")]");
        if (isReq)
        {
            sb.AppendLine($"    {csType} {csParamName}{comma}");
        }
        else
        {
            var nullableType = csType.EndsWith('?') ? csType : csType + "?";
            sb.AppendLine($"    {nullableType} {csParamName} = null{comma}");
        }
    }
    sb.AppendLine(");");
    sb.AppendLine();
}

static string ResolveCsType(JsonElement prop, Dictionary<string, string> nameMap)
{
    if (prop.TryGetProperty("$ref", out var refEl))
    {
        var schemaName = refEl.GetString()!.Replace("#/components/schemas/", "");
        return nameMap.TryGetValue(schemaName, out var csName) ? csName : schemaName.Split('.').Last();
    }

    var type = prop.TryGetProperty("type", out var t) ? t.GetString() : "string";
    var format = prop.TryGetProperty("format", out var f) ? f.GetString() : null;

    return type switch
    {
        "string" when format == "uuid" => "Guid",
        "string" when format == "date-time" => "DateTime",
        "string" => "string",
        "boolean" => "bool",
        "integer" when format == "int64" => "long",
        "integer" => "int",
        "number" => "decimal",
        "array" => ResolveArrayType(prop, nameMap),
        _ => "object"
    };
}

static string ResolveArrayType(JsonElement prop, Dictionary<string, string> nameMap)
{
    if (prop.TryGetProperty("items", out var items))
        return $"List<{ResolveCsType(items, nameMap)}>";
    return "List<object>";
}

static string ToPascalCase(string name)
{
    if (string.IsNullOrEmpty(name)) return name;
    return char.ToUpperInvariant(name[0]) + name[1..];
}

// ======================== Resource generation ========================

static StringBuilder GenerateResources(JsonElement paths, Dictionary<string, string> nameMap)
{
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("// Generated from src/openapi.json (Subiekt 123 API v1.1)");
    sb.AppendLine("// Do not edit manually — regenerate via: dotnet run --project tools/ContractGenerator");
    sb.AppendLine();
    sb.AppendLine("#nullable enable");
    sb.AppendLine();
    sb.AppendLine("using Subiekt.Connector.Contracts;");
    sb.AppendLine();
    sb.AppendLine("namespace Subiekt.Connector.Sdk;");
    sb.AppendLine();

    // Group operations by resource (first path segment)
    var resources = new Dictionary<string, List<ApiOperation>>();
    foreach (var pathProp in paths.EnumerateObject())
    {
        var pathTemplate = pathProp.Name; // e.g. "/clients/{id}"
        var segments = pathTemplate.Trim('/').Split('/');
        var resource = segments[0]; // "clients", "documents", "products"

        foreach (var methodProp in pathProp.Value.EnumerateObject())
        {
            var httpMethod = methodProp.Name.ToUpperInvariant();
            var op = ParseOperation(httpMethod, pathTemplate, methodProp.Value, nameMap, resource);
            if (!resources.ContainsKey(resource))
                resources[resource] = [];
            resources[resource].Add(op);
        }
    }

    foreach (var (resource, ops) in resources.OrderBy(r => r.Key))
    {
        var className = ToPascalCase(resource) + "Resource";
        sb.AppendLine($"public partial class {className}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly SubiektClient _client;");
        sb.AppendLine($"    internal {className}(SubiektClient client) => _client = client;");

        foreach (var op in ops)
        {
            sb.AppendLine();
            GenerateMethod(sb, op);
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    return sb;
}

static ApiOperation ParseOperation(string httpMethod, string path, JsonElement op,
    Dictionary<string, string> nameMap, string resource)
{
    var segments = path.Trim('/').Split('/');
    var hasId = path.Contains("{id}");
    var hasEtag = false;
    var isList = false;
    var returnBytes = false;

    // Check for if-Match header param
    if (op.TryGetProperty("parameters", out var parameters))
    {
        foreach (var p in parameters.EnumerateArray())
        {
            if (p.GetProperty("name").GetString() == "if-Match")
                hasEtag = true;
        }
    }

    // Determine response type from 200 response, application/json content
    string? responseType = null;
    string listItemType = "";
    if (op.TryGetProperty("responses", out var responses) &&
        responses.TryGetProperty("200", out var resp200) &&
        resp200.TryGetProperty("content", out var content))
    {
        if (content.TryGetProperty("application/json", out var jsonContent) &&
            jsonContent.TryGetProperty("schema", out var schema) &&
            schema.TryGetProperty("$ref", out var refEl))
        {
            var schemaName = refEl.GetString()!.Replace("#/components/schemas/", "");
            responseType = nameMap.TryGetValue(schemaName, out var csName) ? csName : schemaName.Split('.').Last();
        }
    }

    // Determine request body type
    string? bodyType = null;
    if (op.TryGetProperty("requestBody", out var reqBody) &&
        reqBody.TryGetProperty("content", out var bodyContent) &&
        bodyContent.TryGetProperty("application/json", out var bodyJson) &&
        bodyJson.TryGetProperty("schema", out var bodySchema) &&
        bodySchema.TryGetProperty("$ref", out var bodyRef))
    {
        var schemaName = bodyRef.GetString()!.Replace("#/components/schemas/", "");
        bodyType = nameMap.TryGetValue(schemaName, out var csName) ? csName : schemaName.Split('.').Last();
    }

    // Determine method name and if it's a list operation
    string methodName;
    if (httpMethod == "GET" && !hasId)
    {
        methodName = "ListAsync";
        isList = true;
        listItemType = responseType ?? "object";
    }
    else if (httpMethod == "GET")
        methodName = "GetAsync";
    else if (httpMethod == "POST" && path.Contains("/printing"))
    {
        methodName = "PrintAsync";
        returnBytes = true;
    }
    else if (httpMethod == "POST")
        methodName = "CreateAsync";
    else if (httpMethod == "PUT")
        methodName = "UpdateAsync";
    else if (httpMethod == "DELETE")
        methodName = "DeleteAsync";
    else if (httpMethod == "PATCH" && path.Contains("/deactivate"))
        methodName = "DeactivateAsync";
    else
        methodName = $"{httpMethod.ToLowerInvariant()}Async";

    return new ApiOperation(httpMethod, path, resource, methodName, responseType, bodyType,
        hasId, hasEtag, isList, listItemType, returnBytes);
}

static void GenerateMethod(StringBuilder sb, ApiOperation op)
{
    var resourcePath = op.Resource;

    if (op.IsList)
    {
        // List method: GET /resources?pageNumber=&pageSize=&filters=&orderBy=
        sb.AppendLine($"    public Task<PagedResult<{op.ListItemType}>> {op.MethodName}(");
        sb.AppendLine($"        int pageNumber = 0, int pageSize = 25,");
        sb.AppendLine($"        string[]? filters = null, string[]? orderBy = null,");
        sb.AppendLine($"        CancellationToken ct = default)");
        sb.AppendLine($"        => _client.GetListAsync<{op.ListItemType}>(");
        sb.AppendLine($"            $\"{resourcePath}{{SubiektClient.BuildListQuery(pageNumber, pageSize, filters, orderBy)}}\", ct);");
    }
    else if (op.HttpMethod == "GET" && op.HasIdParam)
    {
        // Get by ID: GET /resources/{id}
        sb.AppendLine($"    public Task<{op.ResponseType}> {op.MethodName}(Guid id, CancellationToken ct = default)");
        sb.AppendLine($"        => _client.GetAsync<{op.ResponseType}>($\"{resourcePath}/{{id}}\", ct);");
    }
    else if (op.HttpMethod == "POST" && op.ReturnBytes)
    {
        // Print: POST /resources/{id}/printing — returns PDF bytes
        sb.AppendLine($"    public Task<byte[]> {op.MethodName}(Guid id, {op.RequestBodyType} settings, CancellationToken ct = default)");
        sb.AppendLine($"        => _client.PostBytesAsync($\"{resourcePath}/{{id}}/printing\", settings, ct);");
    }
    else if (op.HttpMethod == "POST" && op.RequestBodyType is not null)
    {
        // Create: POST /resources
        sb.AppendLine($"    public Task<{op.ResponseType}> {op.MethodName}({op.RequestBodyType} dto, CancellationToken ct = default)");
        sb.AppendLine($"        => _client.PostAsync<{op.ResponseType}>(\"{resourcePath}\", dto, ct);");
    }
    else if (op.HttpMethod == "PUT" && op.HasEtagParam)
    {
        // Update: PUT /resources/{id} with ETag
        sb.AppendLine($"    public Task<{op.ResponseType}> {op.MethodName}(Guid id, {op.RequestBodyType} dto, string etag, CancellationToken ct = default)");
        sb.AppendLine($"        => _client.PutAsync<{op.ResponseType}>($\"{resourcePath}/{{id}}\", dto, etag, ct);");
    }
    else if (op.HttpMethod == "DELETE")
    {
        // Delete: DELETE /resources/{id}
        sb.AppendLine($"    public Task {op.MethodName}(Guid id, CancellationToken ct = default)");
        sb.AppendLine($"        => _client.DeleteAsync($\"{resourcePath}/{{id}}\", ct);");
    }
    else if (op.HttpMethod == "PATCH" && op.HasIdParam)
    {
        // Patch: PATCH /resources/{id}/action
        var actionSegment = op.Path.Split('/').Last();
        sb.AppendLine($"    public Task {op.MethodName}(Guid id, CancellationToken ct = default)");
        sb.AppendLine($"        => _client.PatchAsync($\"{resourcePath}/{{id}}/{actionSegment}\", ct);");
    }
}

// Type declarations must come after all top-level statements and static methods
record ApiOperation(
    string HttpMethod,
    string Path,
    string Resource,
    string MethodName,
    string? ResponseType,
    string? RequestBodyType,
    bool HasIdParam,
    bool HasEtagParam,
    bool IsList,
    string ListItemType,
    bool ReturnBytes
);
